package org.rdb.expert.export;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.core.Mapper;
import org.rdb.beans.Field;

public interface OracleFieldDao extends Mapper {
	@Select("SELECT M.OWNER SCHEMANAME, M.TABLE_NAME TABLENAME, M.COLUMN_NAME FIELDNAME"
			+ ", M.DATA_TYPE DATATYPE, M.DATA_LENGTH FIELDLEN, M.DATA_PRECISION PRECISION"
			+ ", M.DATA_SCALE SCALE, M.COLUMN_ID FIELDID, M.CHAR_USED CHARUSED, D.COMMENTS REMARK, D.COMMENTS FIELDDESC"
			+ " FROM ALL_TAB_COLUMNS M LEFT JOIN ALL_COL_COMMENTS D "
			+ "	ON M.OWNER = D.OWNER AND M.TABLE_NAME = D.TABLE_NAME"
			+ " AND M.COLUMN_NAME = D.COLUMN_NAME")
	public List<Field> selectAll();

	@Select("SELECT M.OWNER SCHEMANAME, M.TABLE_NAME TABLENAME, M.COLUMN_NAME FIELDNAME"
			+ ", M.DATA_TYPE DATATYPE, M.DATA_LENGTH FIELDLEN, M.DATA_PRECISION PRECISION"
			+ ", M.DATA_SCALE SCALE, M.COLUMN_ID FIELDID, M.CHAR_USED CHARUSED, D.COMMENTS REMARK, D.COMMENTS FIELDDESC"
			+ " FROM ALL_TAB_COLUMNS M LEFT JOIN ALL_COL_COMMENTS D "
			+ "	ON M.OWNER = D.OWNER AND M.TABLE_NAME = D.TABLE_NAME"
			+ " AND M.COLUMN_NAME = D.COLUMN_NAME"
			+ "	WHERE M.OWNER =  #{SchemaName}")
	public List<Field> findBySchema(String SchemaName);

	@Select("SELECT M.OWNER SCHEMANAME, M.TABLE_NAME TABLENAME, M.COLUMN_NAME FIELDNAME"
			+ ", M.DATA_TYPE DATATYPE, M.DATA_LENGTH FIELDLEN, M.DATA_PRECISION PRECISION"
			+ ", M.DATA_SCALE SCALE, M.COLUMN_ID FIELDID, M.CHAR_USED CHARUSED, D.COMMENTS REMARK, D.COMMENTS FIELDDESC"
			+ " FROM ALL_TAB_COLUMNS M LEFT JOIN ALL_COL_COMMENTS D "
			+ "	ON M.OWNER = D.OWNER AND M.TABLE_NAME = D.TABLE_NAME"
			+ " AND M.COLUMN_NAME = D.COLUMN_NAME"
			+ "	WHERE M.TABLE_NAME = #{tableName}")
	public List<Field> findByTable(String tableName);
}